; ****************************************************************************
; 3dc.s (TRDOS 386, TRDOS v2.0 - sample binary file, '3dc.prg')
; ----------------------------------------------------------------------------
; 3DC.PRG ! TEST program !  TRDOS 386 VGA Functionality test !
;
; 05/09/2016 -disassembled source code-
;
; [ Last Modification: 19/05/2026 ] -rewritten using the original source code-
;
; Derived from disassembly of '3D.COM' (MSDOS) intro file
; (10/09/1995, 2113 bytes)
;
; Assembler: NASM 2.11 (3.01, 2026)
;
; Original code disassembler: IDA Pro Free (MASM syntax)
; 
; (Original -msdos- code has been modifed for TRDOS 386 system calls and
; other protected mode (TRDOS 386) interrupts.)
; ****************************************************************************
; nasm 3dc2.s -l 3dc2.txt -o 3DC2.PRG

; Modified from: 3dc.s (05/09/2016)
; ref: 3D.ASM (09-06-1995) ((vulture))

;==============================================================================;
;                                                                              ;
;   Assembler Program By Vulture.                                              ;
;   3D-system example. Use the following formulas to rotate a point:           ;
;                                                                              ;
;        Rotate around x-axis                                                  ;
;        YT = Y * COS(xang) - Z * SIN(xang) / 256                              ;
;        ZT = Y * SIN(xang) + Z * COS(xang) / 256                              ;
;        Y = YT                                                                ;
;        Z = ZT                                                                ;
;                                                                              ;
;        Rotate around y-axis                                                  ;
;        XT = X * COS(yang) - Z * SIN(yang) / 256                              ;
;        ZT = X * SIN(yang) + Z * COS(yang) / 256                              ;
;        X = XT                                                                ;
;        Z = ZT                                                                ;
;                                                                              ;
;        Rotate around z-axis                                                  ;
;        XT = X * COS(zang) - Y * SIN(zang) / 256                              ;
;        YT = X * SIN(zang) + Y * COS(zang) / 256                              ;
;        X = XT                                                                ;
;        Y = YT                                                                ;
;                                                                              ;
;   Divide by 256 coz we have multiplyd our sin values with 256 too.           ;
;   This example isn't too fast right now but it'll work just fine.            ;
;                                                                              ;
;       Current Date: 6-9-95         Vulture                                   ;
;                                                                              ;
;==============================================================================;

; 30/04/2026
; 14/07/2020
; 31/12/2017
; TRDOS 386 (v2.0) system calls
_ver 	equ 0
_exit 	equ 1
_fork 	equ 2
_read 	equ 3
_write	equ 4
_open	equ 5
_close 	equ 6
_wait 	equ 7
_create	equ 8
_rename	equ 9
_delete	equ 10
_exec	equ 11
_chdir	equ 12
_time 	equ 13
_mkdir 	equ 14
_chmod	equ 15
_rmdir	equ 16
_break	equ 17
_drive	equ 18
_seek	equ 19
_tell 	equ 20
_memory	equ 21
_prompt	equ 22
_path	equ 23
_env	equ 24
_stime	equ 25
_quit	equ 26
_intr	equ 27
_dir	equ 28
_emt 	equ 29
_ldrvt 	equ 30
_video 	equ 31
_audio	equ 32
_timer	equ 33
_sleep	equ 34
_msg    equ 35
_geterr	equ 36
_fpstat	equ 37
_pri	equ 38
_rele	equ 39
_fff	equ 40
_fnf	equ 41
_alloc	equ 42
_dalloc equ 43
_calbac equ 44
_dma	equ 45
_stdio	equ 46

%macro sys 1-4
    ; 29/04/2016 - TRDOS 386 (TRDOS v2.0)
    ; 03/09/2015
    ; 13/04/2015
    ; Retro UNIX 386 v1 system call.
    %if %0 >= 2   
        mov ebx, %2
        %if %0 >= 3
            mov ecx, %3
            %if %0 = 4
               mov edx, %4
            %endif
        %endif
    %endif
    mov eax, %1
    ;int 30h
    int 40h ; TRDOS 386 (TRDOS v2.0)
%endmacro

; TRDOS 386 (and Retro UNIX 386 v1) system call format:
; sys systemcall (eax) <arg1 (ebx)>, <arg2 (ecx)>, <arg3 (edx)>


; 3D.ASM
; +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
; +	This file is generated by The Interactive Disassembler (IDA)	    +
; +	Copyright (c) 2010 by Hex-Rays SA, <support@hex-rays.com>	    +
; +			 Licensed to: Freeware version			    +
; +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
;
; Input	MD5   :	99FB4748896801681275A14F458D4563

; File Name   :	C:\dosprogs\PROGRAMS\3D.COM
; Format      :	MS-DOS COM-file
; Base Address:	0h Range: 100h-941h Loaded length: 841h

; NASM version: Erdogan Tan, 14/08/2016

; ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

[BITS 32] ; 80386 Protected Mode (32 bit) intructions

[ORG 0]	  ; (Start at Virtual Address 0)

start:
	; DIRECT VGA MEMORY ACCESS
	;xor	ebx, ebx
	mov	bh, 5 ; Direct access/map to VGA memory (0A0000h)
	;mov	eax, _video ; 1Fh
	mov	al, 1Fh ; sys _video ; TRDOS 386 Video functions
	int	40h   ; TRDOS 386 system call

	; eax = 0A0000h
	and	eax, eax
	jz      terminate ; error (eax = 0)

	;mov     esi, prg_msg
	;call	print_msg

	mov	ax, 13h
	;int	10h		; - VIDEO - SET	VIDEO MODE
				; AL = mode
	int	31h	; TRDOS 386 Video interrupt

	mov	edi, 0A0000h
	mov	esi, Palette	; Set palette
	mov	dx, 3C8h
	xor	al, al
	;out	dx, al

	mov	ah, 1 ; out (byte)
	int	34h ; TRDOS 386 - IOCTL interrupt

	;mov	dx, 3C9h
	inc	edx ; 3C9h

	mov	ecx, 189*3 ; 237h
	;rep outsb
outsb_1:
	lodsb
	;mov	ah, 1 ; out (byte)
	; al = data byte
	; dx = port number
	int	34h ; TRDOS 386 - IOCTL interrupt

	dec	ecx
	jnz	short outsb_1

	; === Set some variables ===
	mov	word [DeltaX], 1 ; Initial speed of rotation
	mov	word [DeltaY], 1 ; Change this and watch
	mov	word [DeltaZ], 1 ; what happens. It's fun!
	mov	word [Xoff], 256 ; 100h
	mov	word [Yoff], 256 ; Used for calculating vga-pos
	mov	word [Zoff], 300 ; 12Ch ; Distance from viewer
MainLoop:
	call	MainProgram

	;in	al, 60h		; AT Keyboard controller 8042.
	;cmp	al, 1
	;jnz	short MainLoop

	mov	ecx, 512
slow_down_cycle:
	nop
	dec	ecx
	jnz	short slow_down_cycle

	mov	ah, 1	; Check keyboard buffer
	int	32h	; TRDOS 386 Keyboard interrupt
	jz	short MainLoop

	mov	ax, 3

	;int	10h	; - VIDEO - SET	VIDEO MODE
			; AL = mode
	int	31h	; TRDOS 386 Video interrupt

	;mov	esi, prg_msg
	mov	esi, Credits
	call	print_msg
terminate:
	sys 	_exit   ; INT 40h
here:
	jmp	short here

; --------------- S U B	R O U T	I N E ---------------------------------------

WaitVrt:
	mov	dx, 3DAh

	mov	ah, 0
Vrt:
	;in	al, dx	; Video	status bits:
			; 0: retrace.  1=display is in vert or horiz retrace.
			; 1: 1=light pen is triggered; 0=armed
			; 2: 1=light pen switch	is open; 0=closed
			; 3: 1=vertical	sync pulse is occurring.

	;mov	ah, 0 ; in (byte)
	int	34h ; TRDOS 386 - IOCTL interrupt

	test	al, 8
	jnz	short Vrt ; Wait until Verticle Retrace starts

NoVrt:
	;in	al, dx	; Video	status bits:
			; 0: retrace.  1=display is in vert or horiz retrace.
			; 1: 1=light pen is triggered; 0=armed
			; 2: 1=light pen switch	is open; 0=closed
			; 3: 1=vertical	sync pulse is occurring.

	;mov	ah, 0 ; in (byte)
	int	34h ; TRDOS 386 - IOCTL interrupt

	test	al, 8
	jz	short NoVrt ; Wait until Verticle Retrace ends
	retn

; --------------- S U B	R O U T	I N E ---------------------------------------

UpdateAngles:
	; Calculates new x,y,z angles
	; to rotate around
	mov	eax, [XAngle]	; Load current angles
	mov	ebx, [YAngle]
	mov	ecx, [ZAngle]

	add	eax, [DeltaX]	; Add velocity
	and	eax, 0FFh	; Range from 0..255
	mov	[XAngle], eax	; Update X
	add	ebx, [DeltaY]	; Add velocity
	and	ebx, 0FFh	; Range from 0..255
	mov	[YAngle], ebx	; Update Y
	add	ecx, [DeltaZ]	; Add velocity
	and	ecx, 0FFh	; Range from 0..255
	mov	[ZAngle], ecx	; Update Z
	retn

; --------------- S U B	R O U T	I N E ---------------------------------------

GetSinCos:
	; Needed : ebx=angle (0..255)
	; Returns: eax=Sin ebx=Cos
	push	ebx		; Save angle (use as pointer)
	shl	ebx, 1		; Grab a word, so ebx=ebx*2
	movsx	eax, word [ebx+SinCos] ; Get sine
	pop	ebx		; Restore pointer into ebx
	add	ebx, 64	; 40h	; Add 64 to get cosine
	and	ebx, 0FFh	; Range from 0..255
	shl	ebx, 1		; * 2 coz it's a word
	movsx	ebx, word [ebx+SinCos] ; Get cosine
	retn

; --------------- S U B	R O U T	I N E ---------------------------------------

SetRotation:
	; Set sine & cosine of x,y,z
	mov	ebx, [XAngle]	; Grab angle
	call	GetSinCos	; Get the sine&cosine
	mov	[XSin], eax	; Save sin
	mov	[XCos], ebx	; Save cos

	mov	ebx, [YAngle]
	call	GetSinCos
	mov	[YSin], eax
	mov	[YCos], ebx

	mov	ebx, [ZAngle]
	call	GetSinCos
	mov	[ZSin], eax
	mov	[ZCos], ebx
	retn

; --------------- S U B	R O U T	I N E ---------------------------------------

RotatePoint:
	; Rotates the point around x,y,z

	; Gets original x,y,z values
	; This can be done elsewhere
	movsx	eax, byte [esi+Cube]	; esi = X (movsx coz of byte)
	mov	[X], eax
	movsx	eax, byte [esi+Cube+1]	; esi+1 = Y
	mov	[Y], eax
	movsx	eax, byte [esi+Cube+2]	; esi+2 = Z
	mov	[Z], eax

	; Rotate around x-axis
	; YT = Y * COS(xang) - Z * SIN(xang) / 256
	; ZT = Y * SIN(xang) + Z * COS(xang) / 256
	; Y = YT
	; Z = ZT
	mov	eax, [Y]
	mov	ebx, [XCos]
	imul	ebx		; eax = Y * Cos(xang)
	mov	ebp, eax
	mov	eax, [Z]
	mov	ebx, [XSin]
	imul	ebx		; eax = Z * Sin(xang)
	sub	ebp, eax	; ebp = Y * Cos(xang) - Z * Sin(xang)
	sar	ebp, 8		; ebp = Y * Cos(xang) - Z * Sin(xang) / 256
	mov	[Yt], ebp

	mov	eax, [Y]
	mov	ebx, [XSin]
	imul	ebx		; eax = Y * Sin(xang)
	mov	ebp, eax
	mov	eax, [Z]
	mov	ebx, [XCos]
	imul	ebx		; eax = Z * Cos(xang)
	add	ebp, eax	; ebp = Y * Sin(xang) + Z * Cos(xang)
	sar	ebp, 8		; ebp = Y * Sing(xang) + Z * Cos(xang) / 256
	mov	[Zt], ebp

	mov	eax, [Yt]	; Switch values
	mov	[Y], eax
	mov	eax, [Zt]
	mov	[Z], eax

	; Rotate around y-axis
	; XT = X * COS(yang) - Z * SIN(yang) / 256
	; ZT = X * SIN(yang) + Z * COS(yang) / 256
	; X = XT
	; Z = ZT
	mov	eax, [X]
	mov	ebx, [YCos]
	imul	ebx		; eax = X * Cos(yang)
	mov	ebp, eax
	mov	eax, [Z]
	mov	ebx, [YSin]
	imul	ebx		; eax = Z * Sin(yang)
	sub	ebp, eax	; ebp = X * Cos(yang) - Z * Sin(yang)
	sar	ebp, 8		; ebp = X * Cos(yang) - Z * Sin(yang) / 256
	mov	[Xt], ebp

	mov	eax, [X]
	mov	ebx, [YSin]
	imul	ebx		; eax = X * Sin(yang)
	mov	ebp, eax
	mov	eax, [Z]
	mov	ebx, [YCos]
	imul	ebx		; eax = Z * Cos(yang)
	add	ebp, eax	; ebp = X * Sin(yang) + Z * Cos(yang)
	sar	ebp, 8		; ebp = X * Sin(yang) + Z * Cos(yang) / 256
	mov	[Zt], ebp

	mov	eax, [Xt]	; Switch values
	mov	[X], eax
	mov	eax, [Zt]
	mov	[Z], eax

	; Rotate around z-axis
	; XT = X * COS(zang) - Y * SIN(zang) / 256
	; YT = X * SIN(zang) + Y * COS(zang) / 256
	; X = XT
	; Y = YT
	mov	eax, [X]
	mov	ebx, [ZCos]
	imul	ebx		; eax = X * Cos(zang)
	mov	ebp, eax
	mov	eax, [Y]
	mov	ebx, [ZSin]
	imul	ebx		; eax = Y * Sin(zang)
	sub	ebp, eax	; ebp = X * Cos(zang) - Y * Sin(zang)
	sar	ebp, 8		; ebp = X * Cos(zang) - Y * Sin(zang) / 256
	mov	[Xt], ebp

	mov	eax, [X]
	mov	ebx, [ZSin]
	imul	ebx		; eax = X * Sin(zang)
	mov	ebp, eax
	mov	eax, [Y]
	mov	ebx, [ZCos]
	imul	ebx		; eax = Y * Cos(zang)
	add	ebp, eax	; ebp = X * Sin(zang) + Y * Cos(zang)
	sar	ebp, 8		; ebp = X * Sin(zang) + Y * Cos(zang) / 256
	mov	[Yt], ebp

	mov	eax, [Xt]	; Switch values
	mov	[X], eax
	mov	eax, [Yt]
	mov	[Y], eax
	retn

; --------------- S U B	R O U T	I N E ---------------------------------------

ShowPoint:
	; Calculates screen position
	; and plots the point on the screen
	mov	eax, [Xoff]	; Xoff*X / Z+Zoff = screen x
	mov	ebx, [X]
	imul	ebx
	mov	ebx, [Z]
	add	ebx, [Zoff]	; Distance
	idiv	ebx
	add	eax, [Mx]	; Center on screen
	mov	ebp, eax
	mov	eax, [Yoff]	; Yoff*Y / Z+Zoff = screen y
	mov	ebx, [Y]
	imul	ebx
	mov	ebx, [Z]
	add	ebx, [Zoff]	; Distance
	idiv	ebx
	add	eax, [My]	; Center on screen
	mov	ebx, 320 ; 140h
	imul	ebx
	add	eax, ebp	; eax = (y*320)+x
	; hw of of edi = 0Ah
	mov	di, ax
	mov	eax, [Z]	; Get color from Z
	add	al, 100	; 64h	; (This piece of code could be improved)
	mov	[edi], al	; Place a dot with color al
	mov	[esi+Erase], di	; Save position for erase
	retn

; --------------- S U B	R O U T	I N E ---------------------------------------

MainProgram:
	call	UpdateAngles	; Calculate new angles
	call	SetRotation	; Find sine & cosine of those angles
	xor	esi, esi	; First 3d-point
	mov	ecx, MaxPoints	; 125
	;nop
ShowLoop:
	call	RotatePoint	; Rotates the point using above formulas
	call	ShowPoint	; Shows the point
	add	esi, 2		; Next 3d-point
	loop	ShowLoop
	call	WaitVrt		; Wait for retrace
	xor	esi, esi	; Starting with point 0
	xor	al, al		; Color = 0 = black
	mov	ecx, MaxPoints	; 7Dh ; 125
	;nop
Deletion:
	mov	di, [esi+Erase] ; di = vgapos old point
	mov	[edi], al
	add	esi, 2
	loop	Deletion
	retn

; --------------- S U B	R O U T	I N E ---------------------------------------

print_msg:
	mov	bx, 7
        mov     ah, 0Eh
pmsg_loop:
	lodsb
	and	al, al
	jz	short pmsg_ok
	int	31h		; TRDOS 386 video interrupt
	jmp	short pmsg_loop
pmsg_ok:
	;mov	ah, 10h		; Getchar
	;int	32h		; TRDOS 386 keyboard interrupt
	retn

;-----------------------------------------------------------------
; data
;-----------------------------------------------------------------

prg_msg:
	db 'ERDOGAN TAN - TRDOS 386 VGA Test - 3DC.PRG'
	db 0Dh,0Ah
	db '05/09/2016 - 19/05/2026'
	db 0Dh,0Ah
	db 0 

; --------------- DATA -----------------------------------------------------

Credits:
	db 13,10,"Code by Vulture / Outlaw Triad",13,10
	;db "$"
	db 0
SinCos:					; 256 values
	dw 0,6,13,19,25,31,38,44,50,56
	dw 62,68,74,80,86,92,98,104,109,115
	dw 121,126,132,137,142,147,152,157,162,167
	dw 172,177,181,185,190,194,198,202,206,209
	dw 213,216,220,223,226,229,231,234,237,239
	dw 241,243,245,247,248,250,251,252,253,254
	dw 255,255,256,256,256,256,256,255,255,254
	dw 253,252,251,250,248,247,245,243,241,239
	dw 237,234,231,229,226,223,220,216,213,209
	dw 206,202,198,194,190,185,181,177,172,167
	dw 162,157,152,147,142,137,132,126,121,115
	dw 109,104,98,92,86,80,74,68,62,56
	dw 50,44,38,31,25,19,13,6,0,-6
	dw -13,-19,-25,-31,-38,-44,-50,-56,-62,-68
	dw -74,-80,-86,-92,-98,-104,-109,-115,-121,-126
	dw -132,-137,-142,-147,-152,-157,-162,-167,-172,-177
	dw -181,-185,-190,-194,-198,-202,-206,-209,-213,-216
	dw -220,-223,-226,-229,-231,-234,-237,-239,-241,-243
	dw -245,-247,-248,-250,-251,-252,-253,-254,-255,-255
	dw -256,-256,-256,-256,-256,-255,-255,-254,-253,-252
	dw -251,-250,-248,-247,-245,-243,-241,-239,-237,-234
	dw -231,-229,-226,-223,-220,-216,-213,-209,-206,-202
	dw -198,-194,-190,-185,-181,-177,-172,-167,-162,-157
	dw -152,-147,-142,-137,-132,-126,-121,-115,-109,-104
	dw -98,-92,-86,-80,-74,-68,-62,-56,-50,-44
	dw -38,-31,-25,-19,-13,-6

Cube:				; The 3d points
	db  -35, -35, -35	; 5x*5y*5z (=125) points
	db  -15, -35, -35	; c = -35 ; rept 5 ; b = -35
	db    5, -35, -35	; rept 5 ; a = -35 ; rept 5
	db   25, -35, -35	; db a,b,c ; a = a + 20
	db   45, -35, -35	; endm ; b = b + 20 ; endm
	db  -35, -15, -35	; c = c + 20 ; endm
	db  -15, -15, -35
	db    5, -15, -35
	db   25, -15, -35
	db   45, -15, -35
	db  -35,   5, -35
	db  -15,   5, -35
	db    5,   5, -35
	db   25,   5, -35
	db   45,   5, -35
	db  -35,  25, -35
	db  -15,  25, -35
	db    5,  25, -35
	db   25,  25, -35
	db   45,  25, -35
	db  -35,  45, -35
	db  -15,  45, -35
	db    5,  45, -35
	db   25,  45, -35
	db   45,  45, -35
	db  -35, -35, -15
	db  -15, -35, -15
	db    5, -35, -15
	db   25, -35, -15
	db   45, -35, -15
	db  -35, -15, -15
	db  -15, -15, -15
	db    5, -15, -15
	db   25, -15, -15
	db   45, -15, -15
	db  -35,   5, -15
	db  -15,   5, -15
	db    5,   5, -15
	db   25,   5, -15
	db   45,   5, -15
	db  -35,  25, -15
	db  -15,  25, -15
	db    5,  25, -15
	db   25,  25, -15
	db   45,  25, -15
	db  -35,  45, -15
	db  -15,  45, -15
	db    5,  45, -15
	db   25,  45, -15
	db   45,  45, -15
	db  -35, -35,	5
	db  -15, -35,	5
	db    5, -35,	5
	db   25, -35,	5
	db   45, -35,	5
	db  -35, -15,	5
	db  -15, -15,	5
	db    5, -15,	5
	db   25, -15,	5
	db   45, -15,	5
	db  -35,   5,	5
	db  -15,   5,	5
	db    5,   5,	5
	db   25,   5,	5
	db   45,   5,	5
	db  -35,  25,	5
	db  -15,  25,	5
	db    5,  25,	5
	db   25,  25,	5
	db   45,  25,	5
	db  -35,  45,	5
	db  -15,  45,	5
	db    5,  45,	5
	db   25,  45,	5
	db   45,  45,	5
	db  -35, -35,  25
	db  -15, -35,  25
	db    5, -35,  25
	db   25, -35,  25
	db   45, -35,  25
	db  -35, -15,  25
	db  -15, -15,  25
	db    5, -15,  25
	db   25, -15,  25
	db   45, -15,  25
	db  -35,   5,  25
	db  -15,   5,  25
	db    5,   5,  25
	db   25,   5,  25
	db   45,   5,  25
	db  -35,  25,  25
	db  -15,  25,  25
	db    5,  25,  25
	db   25,  25,  25
	db   45,  25,  25
	db  -35,  45,  25
	db  -15,  45,  25
	db    5,  45,  25
	db   25,  45,  25
	db   45,  45,  25
	db  -35, -35,  45
	db  -15, -35,  45
	db    5, -35,  45
	db   25, -35,  45
	db   45, -35,  45
	db  -35, -15,  45
	db  -15, -15,  45
	db    5, -15,  45
	db   25, -15,  45
	db   45, -15,  45
	db  -35,   5,  45
	db  -15,   5,  45
	db    5,   5,  45
	db   25,   5,  45
	db   45,   5,  45
	db  -35,  25,  45
	db  -15,  25,  45
	db    5,  25,  45
	db   25,  25,  45
	db   45,  25,  45
	db  -35,  45,  45
	db  -15,  45,  45
	db    5,  45,  45
	db   25,  45,  45
	db   45,  45,  45

Palette:			; The palette to use
	db 0, 0, 0		; 63*3 gray-tint
	db 63, 63, 63, 63, 63, 63, 63, 63, 63	; d = 63
	db 62, 62, 62, 62, 62, 62, 62, 62, 62	; rept 63
	db 61, 61, 61, 61, 61, 61, 61, 61, 61	; db d,d,d
	db 60, 60, 60, 60, 60, 60, 60, 60, 60	; db d,d,d
	db 59, 59, 59, 59, 59, 59, 59, 59, 59	; db d,d,d
	db 58, 58, 58, 58, 58, 58, 58, 58, 58	; d = d - 1
	db 57, 57, 57, 57, 57, 57, 57, 57, 57	; endm
	db 56, 56, 56, 56, 56, 56, 56, 56, 56
	db 55, 55, 55, 55, 55, 55, 55, 55, 55
	db 54, 54, 54, 54, 54, 54, 54, 54, 54
	db 53, 53, 53, 53, 53, 53, 53, 53, 53
	db 52, 52, 52, 52, 52, 52, 52, 52, 52
	db 51, 51, 51, 51, 51, 51, 51, 51, 51
	db 50, 50, 50, 50, 50, 50, 50, 50, 50
	db 49, 49, 49, 49, 49, 49, 49, 49, 49
	db 48, 48, 48, 48, 48, 48, 48, 48, 48
	db 47, 47, 47, 47, 47, 47, 47, 47, 47
	db 46, 46, 46, 46, 46, 46, 46, 46, 46
	db 45, 45, 45, 45, 45, 45, 45, 45, 45
	db 44, 44, 44, 44, 44, 44, 44, 44, 44
	db 43, 43, 43, 43, 43, 43, 43, 43, 43
	db 42, 42, 42, 42, 42, 42, 42, 42, 42
	db 41, 41, 41, 41, 41, 41, 41, 41, 41
	db 40, 40, 40, 40, 40, 40, 40, 40, 40
	db 39, 39, 39, 39, 39, 39, 39, 39, 39
	db 38, 38, 38, 38, 38, 38, 38, 38, 38
	db 37, 37, 37, 37, 37, 37, 37, 37, 37
	db 36, 36, 36, 36, 36, 36, 36, 36, 36
	db 35, 35, 35, 35, 35, 35, 35, 35, 35
	db 34, 34, 34, 34, 34, 34, 34, 34, 34
	db 33, 33, 33, 33, 33, 33, 33, 33, 33
	db 32, 32, 32, 32, 32, 32, 32, 32, 32
	db 31, 31, 31, 31, 31, 31, 31, 31, 31
	db 30, 30, 30, 30, 30, 30, 30, 30, 30
	db 29, 29, 29, 29, 29, 29, 29, 29, 29
	db 28, 28, 28, 28, 28, 28, 28, 28, 28
	db 27, 27, 27, 27, 27, 27, 27, 27, 27
	db 26, 26, 26, 26, 26, 26, 26, 26, 26
	db 25, 25, 25, 25, 25, 25, 25, 25, 25
	db 24, 24, 24, 24, 24, 24, 24, 24, 24
	db 23, 23, 23, 23, 23, 23, 23, 23, 23
	db 22, 22, 22, 22, 22, 22, 22, 22, 22
	db 21, 21, 21, 21, 21, 21, 21, 21, 21
	db 20, 20, 20, 20, 20, 20, 20, 20, 20
	db 19, 19, 19, 19, 19, 19, 19, 19, 19
	db 18, 18, 18, 18, 18, 18, 18, 18, 18
	db 17, 17, 17, 17, 17, 17, 17, 17, 17
	db 16, 16, 16, 16, 16, 16, 16, 16, 16
	db 15, 15, 15, 15, 15, 15, 15, 15, 15
	db 14, 14, 14, 14, 14, 14, 14, 14, 14
	db 13, 13, 13, 13, 13, 13, 13, 13, 13
	db 12, 12, 12, 12, 12, 12, 12, 12, 12
	db 11, 11, 11, 11, 11, 11, 11, 11, 11
	db 10, 10, 10, 10, 10, 10, 10, 10, 10
	db 9, 9, 9, 9, 9, 9, 9, 9, 9
	db 8, 8, 8, 8, 8, 8, 8, 8, 8
	db 7, 7, 7, 7, 7, 7, 7, 7, 7
	db 6, 6, 6, 6, 6, 6, 6, 6, 6
	db 5, 5, 5, 5, 5, 5, 5, 5, 5
	db 4, 4, 4, 4, 4, 4, 4, 4, 4
	db 3, 3, 3, 3, 3, 3, 3, 3, 3
	db 2, 2, 2, 2, 2, 2, 2, 2, 2
	db 1, 1, 1, 1, 1, 1, 1, 1, 1

XAngle:	dd 0		 ; Angle to rotate around x
YAngle:	dd 0
ZAngle:	dd 0

Mx:	dd 160	; 0A0h
My:	dd 100	; 64h

db 0

;-----------------------------------------------------------------
; uninitialized data
;-----------------------------------------------------------------

bss:

ABSOLUTE bss

alignb 4

X:	resd 1		; X variable for formula
Y:	resd 1
Z:	resd 1

Xt:	resd 1		; Temporary variable for x
Yt:	resd 1
Zt:	resd 1

DeltaX:	resd 1		; Amound Xangle is increased each time
DeltaY:	resd 1
DeltaZ:	resd 1

Xoff:	resd 1
Yoff:	resd 1
Zoff:	resd 1		; Distance from viewer

XSin:	resd 1		; Sine and cosine of angle to rotate around
XCos:	resd 1
YSin:	resd 1
YCos:	resd 1
ZSin:	resd 1
ZCos:	resd 1

MaxPoints EQU 125	; Number of 3d Points

Erase:	resw MaxPoints	; Array for deletion screenpoints
_end: