; 3D.ASM
; +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
; +	This file is generated by The Interactive Disassembler (IDA)	    +
; +	Copyright (c) 2010 by Hex-Rays SA, <support@hex-rays.com>	    +
; +			 Licensed to: Freeware version			    +
; +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
;
; Input	MD5   :	99FB4748896801681275A14F458D4563

; File Name   :	C:\dosprogs\PROGRAMS\3D.COM
; Format      :	MS-DOS COM-file
; Base Address:	0h Range: 100h-941h Loaded length: 841h

; NASM version: Erdogan Tan, 14/08/2016

; ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

[BITS 16]

[ORG 100h]

start:
		mov	ax, 13h
		int	10h		; - VIDEO - SET	VIDEO MODE
					; AL = mode
		mov	ax, cs
		mov	ds, ax
		mov	ax, 0A000h
		mov	es, ax
		mov	si, 6D9h
		mov	dx, 3C8h
		xor	al, al
		out	dx, al
		mov	dx, 3C9h
		mov	cx, 237h
		rep outsb
		mov	word [word_925], 1
		mov	word [word_927], 1
		mov	word [word_929], 1
		mov	word [word_92B], 100h
		mov	word [word_92D], 100h
		mov	word [word_92F], 12Ch

loc_143:				; CODE XREF: start+4Aj
		call	sub_310
		in	al, 60h		; AT Keyboard controller 8042.
		cmp	al, 1
		jnz	short loc_143
		mov	ax, 3
		int	10h		; - VIDEO - SET	VIDEO MODE
					; AL = mode
		mov	dx, 33Fh
		mov	ah, 9
		int	21h		; DOS -	PRINT STRING
					; DS:DX	-> string terminated by	"$"
		mov	ax, 4C00h
		int	21h		; DOS -	2+ - QUIT WITH EXIT CODE (EXIT)
					; AL = exit code

; --------------- S U B	R O U T	I N E ---------------------------------------

sub_15D:				; CODE XREF: sub_310+17p
		mov	dx, 3DAh

loc_160:				; CODE XREF: sub_15D+6j
		in	al, dx		; Video	status bits:
					; 0: retrace.  1=display is in vert or horiz retrace.
					; 1: 1=light pen is triggered; 0=armed
					; 2: 1=light pen switch	is open; 0=closed
					; 3: 1=vertical	sync pulse is occurring.
		test	al, 8
		jnz	short loc_160

loc_165:				; CODE XREF: sub_15D+Bj
		in	al, dx		; Video	status bits:
					; 0: retrace.  1=display is in vert or horiz retrace.
					; 1: 1=light pen is triggered; 0=armed
					; 2: 1=light pen switch	is open; 0=closed
					; 3: 1=vertical	sync pulse is occurring.
		test	al, 8
		jz	short loc_165
		retn

; --------------- S U B	R O U T	I N E ---------------------------------------

sub_16B:				; CODE XREF: sub_310p
		mov	ax, [word_91F]
		mov	bx, [word_921]
		mov	cx, [word_923]
		add	ax, [word_925]
		and	ax, 0FFh
		mov	[word_91F], ax
		add	bx, [word_927]
		and	bx, 0FFh
		mov	[word_921], bx
		add	cx, [word_929]
		and	cx, 0FFh
		mov	[word_923], cx
		retn

; --------------- S U B	R O U T	I N E ---------------------------------------

sub_199:				; CODE XREF: sub_1B3+4p sub_1B3+12p ...
		push	bx
		shl	bx, 1
		mov	ax, [bx+362h]
		pop	bx
		push	ax
		add	bx, 40h
		and	bx, 0FFh
		shl	bx, 1
		mov	ax, [bx+362h]
		mov	bx, ax
		pop	ax
		retn

; --------------- S U B	R O U T	I N E ---------------------------------------


sub_1B3:				; CODE XREF: sub_310+3p
		mov	bx, [word_91F]
		call	sub_199
		mov	[word_931], ax
		mov	[word_933], bx
		mov	bx, [word_921]
		call	sub_199
		mov	[word_935], ax
		mov	[word_937], bx
		mov	bx, [word_923]
		call	sub_199
		mov	[word_939], ax
		mov	[word_93B], bx
		retn

; --------------- S U B	R O U T	I N E ---------------------------------------

sub_1DE:				; CODE XREF: sub_310:loc_31Cp
		movsx	ax, byte [si+562h]
		mov	[word_913], ax
		movsx	ax, byte [si+563h]
		mov	[word_915], ax
		movsx	ax, byte [si+564h]
		mov	[word_917], ax
		mov	ax, [word_915]
		mov	bx, [word_933]
		imul	bx
		mov	bp, ax
		mov	ax, [word_917]
		mov	bx, [word_931]
		imul	bx
		sub	bp, ax
		sar	bp, 8
		mov	[word_91B], bp
		mov	ax, [word_915]
		mov	bx, [word_931]
		imul	bx
		mov	bp, ax
		mov	ax, [word_917]
		mov	bx, [word_933]
		imul	bx
		add	bp, ax
		sar	bp, 8
		mov	[word_91D], bp
		mov	ax, [word_91B]
		mov	[word_915], ax
		mov	ax, [word_91D]
		mov	[word_917], ax
		mov	ax, [word_913]
		mov	bx, [word_937]
		imul	bx
		mov	bp, ax
		mov	ax, [word_917]
		mov	bx, [word_935]
		imul	bx
		sub	bp, ax
		sar	bp, 8
		mov	[word_919], bp
		mov	ax, [word_913]
		mov	bx, [word_935]
		imul	bx
		mov	bp, ax
		mov	ax, [word_917]
		mov	bx, [word_937]
		imul	bx
		add	bp, ax
		sar	bp, 8
		mov	[word_91D], bp
		mov	ax, [word_919]
		mov	[word_913], ax
		mov	ax, [word_91D]
		mov	[word_917], ax
		mov	ax, [word_913]
		mov	bx, [word_93B]
		imul	bx
		mov	bp, ax
		mov	ax, [word_915]
		mov	bx, [word_939]
		imul	bx
		sub	bp, ax
		sar	bp, 8
		mov	[word_919], bp
		mov	ax, [word_913]
		mov	bx, [word_939]
		imul	bx
		mov	bp, ax
		mov	ax, [word_915]
		mov	bx, [word_93B]
		imul	bx
		add	bp, ax
		sar	bp, 8
		mov	[word_91B], bp
		mov	ax, [word_919]
		mov	[word_913], ax
		mov	ax, [word_91B]
		mov	[word_915], ax
		retn

; --------------- S U B	R O U T	I N E ---------------------------------------

sub_2C9:				; CODE XREF: sub_310+Fp
		mov	ax, [word_92B]
		mov	bx, [word_913]
		imul	bx
		mov	bx, [word_917]
		add	bx, [word_92F]
		idiv	bx
		add	ax, [word_93D]
		mov	bp, ax
		mov	ax, [word_92D]
		mov	bx, [word_915]
		imul	bx
		mov	bx, [word_917]
		add	bx, [word_92F]
		idiv	bx
		add	ax, [word_93F]
		mov	bx, 140h
		imul	bx
		add	ax, bp
		mov	di, ax
		mov	ax, [word_917]
		add	ax, 64h
		mov	[es:di], al
		mov	[si+941h], di
		retn

; --------------- S U B	R O U T	I N E ---------------------------------------

sub_310:				; CODE XREF: start:loc_143p
		call	sub_16B
		call	sub_1B3
		xor	si, si
		mov	cx, 7Dh
		nop

loc_31C:				; CODE XREF: sub_310+15j
		call	sub_1DE
		call	sub_2C9
		add	si, 3
		loop	loc_31C
		call	sub_15D
		xor	si, si
		xor	al, al
		mov	cx, 7Dh
		nop

loc_332:				; CODE XREF: sub_310+2Cj
		mov	di, [si+941h]
		mov	[es:di], al
		add	si, 3
		loop	loc_332
		retn

; --------------- DATA -----------------------------------------------------

		db  0Dh
		db  0Ah
		db  43h	; C
		db  6Fh	; o
		db  64h	; d
		db  65h	; e
		db  20h
		db  62h	; b
		db  79h	; y
		db  20h
		db  56h	; V
		db  75h	; u
		db  6Ch	; l
		db  74h	; t
		db  75h	; u
		db  72h	; r
		db  65h	; e
		db  20h
		db  2Fh	; /
		db  20h
		db  4Fh	; O
		db  75h	; u
		db  74h	; t
		db  6Ch	; l
		db  61h	; a
		db  77h	; w
		db  20h
		db  54h	; T
		db  72h	; r
		db  69h	; i
		db  61h	; a
		db  64h	; d
		db  0Dh
		db  0Ah
		db  24h	; $
		db    0
		db    0
		db    6
		db    0
		db  0Dh
		db    0
		db  13h
		db    0
		db  19h
		db    0
		db  1Fh
		db    0
		db  26h	; &
		db    0
		db  2Ch	; ,
		db    0
		db  32h	; 2
		db    0
		db  38h	; 8
		db    0
		db  3Eh	; >
		db    0
		db  44h	; D
		db    0
		db  4Ah	; J
		db    0
		db  50h	; P
		db    0
		db  56h	; V
		db    0
		db  5Ch	; \
		db    0
		db  62h	; b
		db    0
		db  68h	; h
		db    0
		db  6Dh	; m
		db    0
		db  73h	; s
		db    0
		db  79h	; y
		db    0
		db  7Eh	; ~
		db    0
		db  84h	; „
		db    0
		db  89h	; ‰
		db    0
		db  8Eh	; Ž
		db    0
		db  93h	; “
		db    0
		db  98h	; ˜
		db    0
		db  9Dh	; 
		db    0
		db 0A2h	; ¢
		db    0
		db 0A7h	; §
		db    0
		db 0ACh	; ¬
		db    0
		db 0B1h	; ±
		db    0
		db 0B5h	; µ
		db    0
		db 0B9h	; ¹
		db    0
		db 0BEh	; ¾
		db    0
		db 0C2h	; Â
		db    0
		db 0C6h	; Æ
		db    0
		db 0CAh	; Ê
		db    0
		db 0CEh	; Î
		db    0
		db 0D1h	; Ñ
		db    0
		db 0D5h	; Õ
		db    0
		db 0D8h	; Ø
		db    0
		db 0DCh	; Ü
		db    0
		db 0DFh	; ß
		db    0
		db 0E2h	; â
		db    0
		db 0E5h	; å
		db    0
		db 0E7h	; ç
		db    0
		db 0EAh	; ê
		db    0
		db 0EDh	; í
		db    0
		db 0EFh	; ï
		db    0
		db 0F1h	; ñ
		db    0
		db 0F3h	; ó
		db    0
		db 0F5h	; õ
		db    0
		db 0F7h	; ÷
		db    0
		db 0F8h	; ø
		db    0
		db 0FAh	; ú
		db    0
		db 0FBh	; û
		db    0
		db 0FCh	; ü
		db    0
		db 0FDh	; ý
		db    0
		db 0FEh	; þ
		db    0
		db 0FFh
		db    0
		db 0FFh
		db    0
		db    0
		db    1
		db    0
		db    1
		db    0
		db    1
		db    0
		db    1
		db    0
		db    1
		db 0FFh
		db    0
		db 0FFh
		db    0
		db 0FEh	; þ
		db    0
		db 0FDh	; ý
		db    0
		db 0FCh	; ü
		db    0
		db 0FBh	; û
		db    0
		db 0FAh	; ú
		db    0
		db 0F8h	; ø
		db    0
		db 0F7h	; ÷
		db    0
		db 0F5h	; õ
		db    0
		db 0F3h	; ó
		db    0
		db 0F1h	; ñ
		db    0
		db 0EFh	; ï
		db    0
		db 0EDh	; í
		db    0
		db 0EAh	; ê
		db    0
		db 0E7h	; ç
		db    0
		db 0E5h	; å
		db    0
		db 0E2h	; â
		db    0
		db 0DFh	; ß
		db    0
		db 0DCh	; Ü
		db    0
		db 0D8h	; Ø
		db    0
		db 0D5h	; Õ
		db    0
		db 0D1h	; Ñ
		db    0
		db 0CEh	; Î
		db    0
		db 0CAh	; Ê
		db    0
		db 0C6h	; Æ
		db    0
		db 0C2h	; Â
		db    0
		db 0BEh	; ¾
		db    0
		db 0B9h	; ¹
		db    0
		db 0B5h	; µ
		db    0
		db 0B1h	; ±
		db    0
		db 0ACh	; ¬
		db    0
		db 0A7h	; §
		db    0
		db 0A2h	; ¢
		db    0
		db  9Dh	; 
		db    0
		db  98h	; ˜
		db    0
		db  93h	; “
		db    0
		db  8Eh	; Ž
		db    0
		db  89h	; ‰
		db    0
		db  84h	; „
		db    0
		db  7Eh	; ~
		db    0
		db  79h	; y
		db    0
		db  73h	; s
		db    0
		db  6Dh	; m
		db    0
		db  68h	; h
		db    0
		db  62h	; b
		db    0
		db  5Ch	; \
		db    0
		db  56h	; V
		db    0
		db  50h	; P
		db    0
		db  4Ah	; J
		db    0
		db  44h	; D
		db    0
		db  3Eh	; >
		db    0
		db  38h	; 8
		db    0
		db  32h	; 2
		db    0
		db  2Ch	; ,
		db    0
		db  26h	; &
		db    0
		db  1Fh
		db    0
		db  19h
		db    0
		db  13h
		db    0
		db  0Dh
		db    0
		db    6
		db    0
		db    0
		db    0
		db 0FAh	; ú
		db 0FFh
		db 0F3h	; ó
		db 0FFh
		db 0EDh	; í
		db 0FFh
		db 0E7h	; ç
		db 0FFh
		db 0E1h	; á
		db 0FFh
		db 0DAh	; Ú
		db 0FFh
		db 0D4h	; Ô
		db 0FFh
		db 0CEh	; Î
		db 0FFh
		db 0C8h	; È
		db 0FFh
		db 0C2h	; Â
		db 0FFh
		db 0BCh	; ¼
		db 0FFh
		db 0B6h	; ¶
		db 0FFh
		db 0B0h	; °
		db 0FFh
		db 0AAh	; ª
		db 0FFh
		db 0A4h	; ¤
		db 0FFh
		db  9Eh	; ž
		db 0FFh
		db  98h	; ˜
		db 0FFh
		db  93h	; “
		db 0FFh
		db  8Dh	; 
		db 0FFh
		db  87h	; ‡
		db 0FFh
		db  82h	; ‚
		db 0FFh
		db  7Ch	; |
		db 0FFh
		db  77h	; w
		db 0FFh
		db  72h	; r
		db 0FFh
		db  6Dh	; m
		db 0FFh
		db  68h	; h
		db 0FFh
		db  63h	; c
		db 0FFh
		db  5Eh	; ^
		db 0FFh
		db  59h	; Y
		db 0FFh
		db  54h	; T
		db 0FFh
		db  4Fh	; O
		db 0FFh
		db  4Bh	; K
		db 0FFh
		db  47h	; G
		db 0FFh
		db  42h	; B
		db 0FFh
		db  3Eh	; >
		db 0FFh
		db  3Ah	; :
		db 0FFh
		db  36h	; 6
		db 0FFh
		db  32h	; 2
		db 0FFh
		db  2Fh	; /
		db 0FFh
		db  2Bh	; +
		db 0FFh
		db  28h	; (
		db 0FFh
		db  24h	; $
		db 0FFh
		db  21h	; !
		db 0FFh
		db  1Eh
		db 0FFh
		db  1Bh
		db 0FFh
		db  19h
		db 0FFh
		db  16h
		db 0FFh
		db  13h
		db 0FFh
		db  11h
		db 0FFh
		db  0Fh
		db 0FFh
		db  0Dh
		db 0FFh
		db  0Bh
		db 0FFh
		db    9
		db 0FFh
		db    8
		db 0FFh
		db    6
		db 0FFh
		db    5
		db 0FFh
		db    4
		db 0FFh
		db    3
		db 0FFh
		db    2
		db 0FFh
		db    1
		db 0FFh
		db    1
		db 0FFh
		db    0
		db 0FFh
		db    0
		db 0FFh
		db    0
		db 0FFh
		db    0
		db 0FFh
		db    0
		db 0FFh
		db    1
		db 0FFh
		db    1
		db 0FFh
		db    2
		db 0FFh
		db    3
		db 0FFh
		db    4
		db 0FFh
		db    5
		db 0FFh
		db    6
		db 0FFh
		db    8
		db 0FFh
		db    9
		db 0FFh
		db  0Bh
		db 0FFh
		db  0Dh
		db 0FFh
		db  0Fh
		db 0FFh
		db  11h
		db 0FFh
		db  13h
		db 0FFh
		db  16h
		db 0FFh
		db  19h
		db 0FFh
		db  1Bh
		db 0FFh
		db  1Eh
		db 0FFh
		db  21h	; !
		db 0FFh
		db  24h	; $
		db 0FFh
		db  28h	; (
		db 0FFh
		db  2Bh	; +
		db 0FFh
		db  2Fh	; /
		db 0FFh
		db  32h	; 2
		db 0FFh
		db  36h	; 6
		db 0FFh
		db  3Ah	; :
		db 0FFh
		db  3Eh	; >
		db 0FFh
		db  42h	; B
		db 0FFh
		db  47h	; G
		db 0FFh
		db  4Bh	; K
		db 0FFh
		db  4Fh	; O
		db 0FFh
		db  54h	; T
		db 0FFh
		db  59h	; Y
		db 0FFh
		db  5Eh	; ^
		db 0FFh
		db  63h	; c
		db 0FFh
		db  68h	; h
		db 0FFh
		db  6Dh	; m
		db 0FFh
		db  72h	; r
		db 0FFh
		db  77h	; w
		db 0FFh
		db  7Ch	; |
		db 0FFh
		db  82h	; ‚
		db 0FFh
		db  87h	; ‡
		db 0FFh
		db  8Dh	; 
		db 0FFh
		db  93h	; “
		db 0FFh
		db  98h	; ˜
		db 0FFh
		db  9Eh	; ž
		db 0FFh
		db 0A4h	; ¤
		db 0FFh
		db 0AAh	; ª
		db 0FFh
		db 0B0h	; °
		db 0FFh
		db 0B6h	; ¶
		db 0FFh
		db 0BCh	; ¼
		db 0FFh
		db 0C2h	; Â
		db 0FFh
		db 0C8h	; È
		db 0FFh
		db 0CEh	; Î
		db 0FFh
		db 0D4h	; Ô
		db 0FFh
		db 0DAh	; Ú
		db 0FFh
		db 0E1h	; á
		db 0FFh
		db 0E7h	; ç
		db 0FFh
		db 0EDh	; í
		db 0FFh
		db 0F3h	; ó
		db 0FFh
		db 0FAh	; ú
		db 0FFh
		db 0DDh	; Ý
		db 0DDh	; Ý
		db 0DDh	; Ý
		db 0F1h	; ñ
		db 0DDh	; Ý
		db 0DDh	; Ý
		db    5
		db 0DDh	; Ý
		db 0DDh	; Ý
		db  19h
		db 0DDh	; Ý
		db 0DDh	; Ý
		db  2Dh	; -
		db 0DDh	; Ý
		db 0DDh	; Ý
		db 0DDh	; Ý
		db 0F1h	; ñ
		db 0DDh	; Ý
		db 0F1h	; ñ
		db 0F1h	; ñ
		db 0DDh	; Ý
		db    5
		db 0F1h	; ñ
		db 0DDh	; Ý
		db  19h
		db 0F1h	; ñ
		db 0DDh	; Ý
		db  2Dh	; -
		db 0F1h	; ñ
		db 0DDh	; Ý
		db 0DDh	; Ý
		db    5
		db 0DDh	; Ý
		db 0F1h	; ñ
		db    5
		db 0DDh	; Ý
		db    5
		db    5
		db 0DDh	; Ý
		db  19h
		db    5
		db 0DDh	; Ý
		db  2Dh	; -
		db    5
		db 0DDh	; Ý
		db 0DDh	; Ý
		db  19h
		db 0DDh	; Ý
		db 0F1h	; ñ
		db  19h
		db 0DDh	; Ý
		db    5
		db  19h
		db 0DDh	; Ý
		db  19h
		db  19h
		db 0DDh	; Ý
		db  2Dh	; -
		db  19h
		db 0DDh	; Ý
		db 0DDh	; Ý
		db  2Dh	; -
		db 0DDh	; Ý
		db 0F1h	; ñ
		db  2Dh	; -
		db 0DDh	; Ý
		db    5
		db  2Dh	; -
		db 0DDh	; Ý
		db  19h
		db  2Dh	; -
		db 0DDh	; Ý
		db  2Dh	; -
		db  2Dh	; -
		db 0DDh	; Ý
		db 0DDh	; Ý
		db 0DDh	; Ý
		db 0F1h	; ñ
		db 0F1h	; ñ
		db 0DDh	; Ý
		db 0F1h	; ñ
		db    5
		db 0DDh	; Ý
		db 0F1h	; ñ
		db  19h
		db 0DDh	; Ý
		db 0F1h	; ñ
		db  2Dh	; -
		db 0DDh	; Ý
		db 0F1h	; ñ
		db 0DDh	; Ý
		db 0F1h	; ñ
		db 0F1h	; ñ
		db 0F1h	; ñ
		db 0F1h	; ñ
		db 0F1h	; ñ
		db    5
		db 0F1h	; ñ
		db 0F1h	; ñ
		db  19h
		db 0F1h	; ñ
		db 0F1h	; ñ
		db  2Dh	; -
		db 0F1h	; ñ
		db 0F1h	; ñ
		db 0DDh	; Ý
		db    5
		db 0F1h	; ñ
		db 0F1h	; ñ
		db    5
		db 0F1h	; ñ
		db    5
		db    5
		db 0F1h	; ñ
		db  19h
		db    5
		db 0F1h	; ñ
		db  2Dh	; -
		db    5
		db 0F1h	; ñ
		db 0DDh	; Ý
		db  19h
		db 0F1h	; ñ
		db 0F1h	; ñ
		db  19h
		db 0F1h	; ñ
		db    5
		db  19h
		db 0F1h	; ñ
		db  19h
		db  19h
		db 0F1h	; ñ
		db  2Dh	; -
		db  19h
		db 0F1h	; ñ
		db 0DDh	; Ý
		db  2Dh	; -
		db 0F1h	; ñ
		db 0F1h	; ñ
		db  2Dh	; -
		db 0F1h	; ñ
		db    5
		db  2Dh	; -
		db 0F1h	; ñ
		db  19h
		db  2Dh	; -
		db 0F1h	; ñ
		db  2Dh	; -
		db  2Dh	; -
		db 0F1h	; ñ
		db 0DDh	; Ý
		db 0DDh	; Ý
		db    5
		db 0F1h	; ñ
		db 0DDh	; Ý
		db    5
		db    5
		db 0DDh	; Ý
		db    5
		db  19h
		db 0DDh	; Ý
		db    5
		db  2Dh	; -
		db 0DDh	; Ý
		db    5
		db 0DDh	; Ý
		db 0F1h	; ñ
		db    5
		db 0F1h	; ñ
		db 0F1h	; ñ
		db    5
		db    5
		db 0F1h	; ñ
		db    5
		db  19h
		db 0F1h	; ñ
		db    5
		db  2Dh	; -
		db 0F1h	; ñ
		db    5
		db 0DDh	; Ý
		db    5
		db    5
		db 0F1h	; ñ
		db    5
		db    5
		db    5
		db    5
		db    5
		db  19h
		db    5
		db    5
		db  2Dh	; -
		db    5
		db    5
		db 0DDh	; Ý
		db  19h
		db    5
		db 0F1h	; ñ
		db  19h
		db    5
		db    5
		db  19h
		db    5
		db  19h
		db  19h
		db    5
		db  2Dh	; -
		db  19h
		db    5
		db 0DDh	; Ý
		db  2Dh	; -
		db    5
		db 0F1h	; ñ
		db  2Dh	; -
		db    5
		db    5
		db  2Dh	; -
		db    5
		db  19h
		db  2Dh	; -
		db    5
		db  2Dh	; -
		db  2Dh	; -
		db    5
		db 0DDh	; Ý
		db 0DDh	; Ý
		db  19h
		db 0F1h	; ñ
		db 0DDh	; Ý
		db  19h
		db    5
		db 0DDh	; Ý
		db  19h
		db  19h
		db 0DDh	; Ý
		db  19h
		db  2Dh	; -
		db 0DDh	; Ý
		db  19h
		db 0DDh	; Ý
		db 0F1h	; ñ
		db  19h
		db 0F1h	; ñ
		db 0F1h	; ñ
		db  19h
		db    5
		db 0F1h	; ñ
		db  19h
		db  19h
		db 0F1h	; ñ
		db  19h
		db  2Dh	; -
		db 0F1h	; ñ
		db  19h
		db 0DDh	; Ý
		db    5
		db  19h
		db 0F1h	; ñ
		db    5
		db  19h
		db    5
		db    5
		db  19h
		db  19h
		db    5
		db  19h
		db  2Dh	; -
		db    5
		db  19h
		db 0DDh	; Ý
		db  19h
		db  19h
		db 0F1h	; ñ
		db  19h
		db  19h
		db    5
		db  19h
		db  19h
		db  19h
		db  19h
		db  19h
		db  2Dh	; -
		db  19h
		db  19h
		db 0DDh	; Ý
		db  2Dh	; -
		db  19h
		db 0F1h	; ñ
		db  2Dh	; -
		db  19h
		db    5
		db  2Dh	; -
		db  19h
		db  19h
		db  2Dh	; -
		db  19h
		db  2Dh	; -
		db  2Dh	; -
		db  19h
		db 0DDh	; Ý
		db 0DDh	; Ý
		db  2Dh	; -
		db 0F1h	; ñ
		db 0DDh	; Ý
		db  2Dh	; -
		db    5
		db 0DDh	; Ý
		db  2Dh	; -
		db  19h
		db 0DDh	; Ý
		db  2Dh	; -
		db  2Dh	; -
		db 0DDh	; Ý
		db  2Dh	; -
		db 0DDh	; Ý
		db 0F1h	; ñ
		db  2Dh	; -
		db 0F1h	; ñ
		db 0F1h	; ñ
		db  2Dh	; -
		db    5
		db 0F1h	; ñ
		db  2Dh	; -
		db  19h
		db 0F1h	; ñ
		db  2Dh	; -
		db  2Dh	; -
		db 0F1h	; ñ
		db  2Dh	; -
		db 0DDh	; Ý
		db    5
		db  2Dh	; -
		db 0F1h	; ñ
		db    5
		db  2Dh	; -
		db    5
		db    5
		db  2Dh	; -
		db  19h
		db    5
		db  2Dh	; -
		db  2Dh	; -
		db    5
		db  2Dh	; -
		db 0DDh	; Ý
		db  19h
		db  2Dh	; -
		db 0F1h	; ñ
		db  19h
		db  2Dh	; -
		db    5
		db  19h
		db  2Dh	; -
		db  19h
		db  19h
		db  2Dh	; -
		db  2Dh	; -
		db  19h
		db  2Dh	; -
		db 0DDh	; Ý
		db  2Dh	; -
		db  2Dh	; -
		db 0F1h	; ñ
		db  2Dh	; -
		db  2Dh	; -
		db    5
		db  2Dh	; -
		db  2Dh	; -
		db  19h
		db  2Dh	; -
		db  2Dh	; -
		db  2Dh	; -
		db  2Dh	; -
		db  2Dh	; -
		db    0
		db    0
		db    0
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Eh	; >
		db  3Eh	; >
		db  3Eh	; >
		db  3Eh	; >
		db  3Eh	; >
		db  3Eh	; >
		db  3Eh	; >
		db  3Eh	; >
		db  3Eh	; >
		db  3Dh	; =
		db  3Dh	; =
		db  3Dh	; =
		db  3Dh	; =
		db  3Dh	; =
		db  3Dh	; =
		db  3Dh	; =
		db  3Dh	; =
		db  3Dh	; =
		db  3Ch	; <
		db  3Ch	; <
		db  3Ch	; <
		db  3Ch	; <
		db  3Ch	; <
		db  3Ch	; <
		db  3Ch	; <
		db  3Ch	; <
		db  3Ch	; <
		db  3Bh	; ;
		db  3Bh	; ;
		db  3Bh	; ;
		db  3Bh	; ;
		db  3Bh	; ;
		db  3Bh	; ;
		db  3Bh	; ;
		db  3Bh	; ;
		db  3Bh	; ;
		db  3Ah	; :
		db  3Ah	; :
		db  3Ah	; :
		db  3Ah	; :
		db  3Ah	; :
		db  3Ah	; :
		db  3Ah	; :
		db  3Ah	; :
		db  3Ah	; :
		db  39h	; 9
		db  39h	; 9
		db  39h	; 9
		db  39h	; 9
		db  39h	; 9
		db  39h	; 9
		db  39h	; 9
		db  39h	; 9
		db  39h	; 9
		db  38h	; 8
		db  38h	; 8
		db  38h	; 8
		db  38h	; 8
		db  38h	; 8
		db  38h	; 8
		db  38h	; 8
		db  38h	; 8
		db  38h	; 8
		db  37h	; 7
		db  37h	; 7
		db  37h	; 7
		db  37h	; 7
		db  37h	; 7
		db  37h	; 7
		db  37h	; 7
		db  37h	; 7
		db  37h	; 7
		db  36h	; 6
		db  36h	; 6
		db  36h	; 6
		db  36h	; 6
		db  36h	; 6
		db  36h	; 6
		db  36h	; 6
		db  36h	; 6
		db  36h	; 6
		db  35h	; 5
		db  35h	; 5
		db  35h	; 5
		db  35h	; 5
		db  35h	; 5
		db  35h	; 5
		db  35h	; 5
		db  35h	; 5
		db  35h	; 5
		db  34h	; 4
		db  34h	; 4
		db  34h	; 4
		db  34h	; 4
		db  34h	; 4
		db  34h	; 4
		db  34h	; 4
		db  34h	; 4
		db  34h	; 4
		db  33h	; 3
		db  33h	; 3
		db  33h	; 3
		db  33h	; 3
		db  33h	; 3
		db  33h	; 3
		db  33h	; 3
		db  33h	; 3
		db  33h	; 3
		db  32h	; 2
		db  32h	; 2
		db  32h	; 2
		db  32h	; 2
		db  32h	; 2
		db  32h	; 2
		db  32h	; 2
		db  32h	; 2
		db  32h	; 2
		db  31h	; 1
		db  31h	; 1
		db  31h	; 1
		db  31h	; 1
		db  31h	; 1
		db  31h	; 1
		db  31h	; 1
		db  31h	; 1
		db  31h	; 1
		db  30h	; 0
		db  30h	; 0
		db  30h	; 0
		db  30h	; 0
		db  30h	; 0
		db  30h	; 0
		db  30h	; 0
		db  30h	; 0
		db  30h	; 0
		db  2Fh	; /
		db  2Fh	; /
		db  2Fh	; /
		db  2Fh	; /
		db  2Fh	; /
		db  2Fh	; /
		db  2Fh	; /
		db  2Fh	; /
		db  2Fh	; /
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  2Eh	; .
		db  2Dh	; -
		db  2Dh	; -
		db  2Dh	; -
		db  2Dh	; -
		db  2Dh	; -
		db  2Dh	; -
		db  2Dh	; -
		db  2Dh	; -
		db  2Dh	; -
		db  2Ch	; ,
		db  2Ch	; ,
		db  2Ch	; ,
		db  2Ch	; ,
		db  2Ch	; ,
		db  2Ch	; ,
		db  2Ch	; ,
		db  2Ch	; ,
		db  2Ch	; ,
		db  2Bh	; +
		db  2Bh	; +
		db  2Bh	; +
		db  2Bh	; +
		db  2Bh	; +
		db  2Bh	; +
		db  2Bh	; +
		db  2Bh	; +
		db  2Bh	; +
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  2Ah	; *
		db  29h	; )
		db  29h	; )
		db  29h	; )
		db  29h	; )
		db  29h	; )
		db  29h	; )
		db  29h	; )
		db  29h	; )
		db  29h	; )
		db  28h	; (
		db  28h	; (
		db  28h	; (
		db  28h	; (
		db  28h	; (
		db  28h	; (
		db  28h	; (
		db  28h	; (
		db  28h	; (
		db  27h	; '
		db  27h	; '
		db  27h	; '
		db  27h	; '
		db  27h	; '
		db  27h	; '
		db  27h	; '
		db  27h	; '
		db  27h	; '
		db  26h	; &
		db  26h	; &
		db  26h	; &
		db  26h	; &
		db  26h	; &
		db  26h	; &
		db  26h	; &
		db  26h	; &
		db  26h	; &
		db  25h	; %
		db  25h	; %
		db  25h	; %
		db  25h	; %
		db  25h	; %
		db  25h	; %
		db  25h	; %
		db  25h	; %
		db  25h	; %
		db  24h	; $
		db  24h	; $
		db  24h	; $
		db  24h	; $
		db  24h	; $
		db  24h	; $
		db  24h	; $
		db  24h	; $
		db  24h	; $
		db  23h	; #
		db  23h	; #
		db  23h	; #
		db  23h	; #
		db  23h	; #
		db  23h	; #
		db  23h	; #
		db  23h	; #
		db  23h	; #
		db  22h	; "
		db  22h	; "
		db  22h	; "
		db  22h	; "
		db  22h	; "
		db  22h	; "
		db  22h	; "
		db  22h	; "
		db  22h	; "
		db  21h	; !
		db  21h	; !
		db  21h	; !
		db  21h	; !
		db  21h	; !
		db  21h	; !
		db  21h	; !
		db  21h	; !
		db  21h	; !
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  1Fh
		db  1Fh
		db  1Fh
		db  1Fh
		db  1Fh
		db  1Fh
		db  1Fh
		db  1Fh
		db  1Fh
		db  1Eh
		db  1Eh
		db  1Eh
		db  1Eh
		db  1Eh
		db  1Eh
		db  1Eh
		db  1Eh
		db  1Eh
		db  1Dh
		db  1Dh
		db  1Dh
		db  1Dh
		db  1Dh
		db  1Dh
		db  1Dh
		db  1Dh
		db  1Dh
		db  1Ch
		db  1Ch
		db  1Ch
		db  1Ch
		db  1Ch
		db  1Ch
		db  1Ch
		db  1Ch
		db  1Ch
		db  1Bh
		db  1Bh
		db  1Bh
		db  1Bh
		db  1Bh
		db  1Bh
		db  1Bh
		db  1Bh
		db  1Bh
		db  1Ah
		db  1Ah
		db  1Ah
		db  1Ah
		db  1Ah
		db  1Ah
		db  1Ah
		db  1Ah
		db  1Ah
		db  19h
		db  19h
		db  19h
		db  19h
		db  19h
		db  19h
		db  19h
		db  19h
		db  19h
		db  18h
		db  18h
		db  18h
		db  18h
		db  18h
		db  18h
		db  18h
		db  18h
		db  18h
		db  17h
		db  17h
		db  17h
		db  17h
		db  17h
		db  17h
		db  17h
		db  17h
		db  17h
		db  16h
		db  16h
		db  16h
		db  16h
		db  16h
		db  16h
		db  16h
		db  16h
		db  16h
		db  15h
		db  15h
		db  15h
		db  15h
		db  15h
		db  15h
		db  15h
		db  15h
		db  15h
		db  14h
		db  14h
		db  14h
		db  14h
		db  14h
		db  14h
		db  14h
		db  14h
		db  14h
		db  13h
		db  13h
		db  13h
		db  13h
		db  13h
		db  13h
		db  13h
		db  13h
		db  13h
		db  12h
		db  12h
		db  12h
		db  12h
		db  12h
		db  12h
		db  12h
		db  12h
		db  12h
		db  11h
		db  11h
		db  11h
		db  11h
		db  11h
		db  11h
		db  11h
		db  11h
		db  11h
		db  10h
		db  10h
		db  10h
		db  10h
		db  10h
		db  10h
		db  10h
		db  10h
		db  10h
		db  0Fh
		db  0Fh
		db  0Fh
		db  0Fh
		db  0Fh
		db  0Fh
		db  0Fh
		db  0Fh
		db  0Fh
		db  0Eh
		db  0Eh
		db  0Eh
		db  0Eh
		db  0Eh
		db  0Eh
		db  0Eh
		db  0Eh
		db  0Eh
		db  0Dh
		db  0Dh
		db  0Dh
		db  0Dh
		db  0Dh
		db  0Dh
		db  0Dh
		db  0Dh
		db  0Dh
		db  0Ch
		db  0Ch
		db  0Ch
		db  0Ch
		db  0Ch
		db  0Ch
		db  0Ch
		db  0Ch
		db  0Ch
		db  0Bh
		db  0Bh
		db  0Bh
		db  0Bh
		db  0Bh
		db  0Bh
		db  0Bh
		db  0Bh
		db  0Bh
		db  0Ah
		db  0Ah
		db  0Ah
		db  0Ah
		db  0Ah
		db  0Ah
		db  0Ah
		db  0Ah
		db  0Ah
		db    9
		db    9
		db    9
		db    9
		db    9
		db    9
		db    9
		db    9
		db    9
		db    8
		db    8
		db    8
		db    8
		db    8
		db    8
		db    8
		db    8
		db    8
		db    7
		db    7
		db    7
		db    7
		db    7
		db    7
		db    7
		db    7
		db    7
		db    6
		db    6
		db    6
		db    6
		db    6
		db    6
		db    6
		db    6
		db    6
		db    5
		db    5
		db    5
		db    5
		db    5
		db    5
		db    5
		db    5
		db    5
		db    4
		db    4
		db    4
		db    4
		db    4
		db    4
		db    4
		db    4
		db    4
		db    3
		db    3
		db    3
		db    3
		db    3
		db    3
		db    3
		db    3
		db    3
		db    2
		db    2
		db    2
		db    2
		db    2
		db    2
		db    2
		db    2
		db    2
		db    1
		db    1
		db    1
		db    1
		db    1
		db    1
		db    1
		db    1
		db    1
word_913:	dw 0			; DATA XREF: sub_1DE+5w sub_1DE+5Er ...
word_915:	dw 0			; DATA XREF: sub_1DE+Dw sub_1DE+18r ...
word_917:	dw 0			; DATA XREF: sub_1DE+15w sub_1DE+23r ...
word_919:	dw 0			; DATA XREF: sub_1DE+77w sub_1DE+98r ...
word_91B:	dw 0			; DATA XREF: sub_1DE+31w sub_1DE+52r ...
word_91D:	dw 0			; DATA XREF: sub_1DE+4Ew sub_1DE+58r ...
word_91F:	dw 0			; DATA XREF: sub_16Br sub_16B+12w ...
word_921:	dw 0			; DATA XREF: sub_16B+3r sub_16B+1Dw ...
word_923:	dw 0			; DATA XREF: sub_16B+7r sub_16B+29w ...
word_925:	dw 0			; DATA XREF: start+1Fw	sub_16B+Br
word_927:	dw 0			; DATA XREF: start+25w	sub_16B+15r
word_929:	dw 0			; DATA XREF: start+2Bw	sub_16B+21r
word_92B:	dw 0			; DATA XREF: start+31w	sub_2C9r
word_92D:	dw 0			; DATA XREF: start+37w	sub_2C9+19r
word_92F:	dw 0			; DATA XREF: start+3Dw	sub_2C9+Dr ...
word_931:	dw 0			; DATA XREF: sub_1B3+7w sub_1DE+26r ...
word_933:	dw 0			; DATA XREF: sub_1B3+Aw sub_1DE+1Br ...
word_935:	dw 0			; DATA XREF: sub_1B3+15w sub_1DE+6Cr ...
word_937:	dw 0			; DATA XREF: sub_1B3+18w sub_1DE+61r ...
word_939:	dw 0			; DATA XREF: sub_1B3+23w sub_1DE+B2r ...
word_93B:	dw 0			; DATA XREF: sub_1B3+26w sub_1DE+A7r ...
word_93D:	dw 0A0h			; DATA XREF: sub_2C9+13r
word_93F:	dw 64h			; DATA XREF: sub_2C9+2Cr

_end: