; FLAMES.ASM
; +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
; +	This file is generated by The Interactive Disassembler (IDA)	    +
; +	Copyright (c) 2010 by Hex-Rays SA, <support@hex-rays.com>	    +
; +			 Licensed to: Freeware version			    +
; +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
;
; Input	MD5   :	603DA1DA67C2ECDB6D661B4EEA091F69

; File Name   :	C:\Documents and Settings\Erdoðan Tan\Desktop\FLAMES.COM
; Format      :	MS-DOS COM-file
; Base Address:	1000h Range: 10100h-13BFBh Loaded length: 3AFBh

; NASM version: Erdogan Tan, 14/08/2016

; ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

[BITS 16]

[ORG 100h]

start:
		mov	ax, 13h
		int	10h		; - VIDEO - SET	VIDEO MODE
					; AL = mode
		mov	dx, 3C4h
		;mov	ax, 604h
		;out	dx, ax		; EGA: sequencer address reg
					; unknown register
		mov	al, 04h
		out	dx, al
		inc	dx
		mov	al, 06h
		out	dx, al

		;mov	dx, 3C4h
		;mov	ax, 0F02h
		;out	dx, ax		; EGA: sequencer address reg
					; unknown register
		
		dec	dx
		mov	al, 02h
		out	dx, al
		inc	dx
		mov	al, 0Fh
		out	dx, al

		mov	ax, 0A000h
		mov	es, ax
		xor	di, di
		xor	ax, ax
		mov	cx, 8000h
		cld
		rep stosw
		
		;mov	dx, 3D4h
		;mov	ax, 14h
		;out	dx, ax		; Video: CRT cntrlr addr
					; underline location.  Bits 0-5	are scan line number.
	
		mov	dx, 3D4h
		mov	al, 14h
		out	dx, al
		inc	dx
		mov	al, 0
		out	dx, al

		;mov	ax, 0E317h
		;out	dx, ax		; Video: CRT cntrlr addr
					;
		dec	dx
		mov	al, 17h
		out	dx, al
		inc	dx
		mov	al, 0E3h
		out	dx, al

		;mov	ax, 409h
		;out	dx, ax		; Video: CRT cntrlr addr
					;
		dec	dx
		mov	al, 09h
		out	dx, al
		inc	dx
		mov	al, 04h
		out	dx, al

		call	sub_101DF
	
		lea	si, [unk_138FB]
		mov	cx, 300h
		mov	dx, 3C8h
		xor	al, al
		out	dx, al
		inc	dx
		;cld
		;rep outsb
outsb_1:
		lodsb
		out	dx, al
		dec	cx
		jnz	short outsb_1
		
		mov	ax, ds
		mov	es, ax
		lea	di, [unk_101F9]
		mov	cx, 1B80h
		xor	ax, ax
		rep stosw
		mov	ax, 0A000h
		mov	es, ax
		mov	bx, 4
		xor	bp, bp

loc_1015E:				; CODE XREF: start+D0j	start+D6j
		call	sub_101DF
		lea	si, [unk_101F9]
		xor	di, di
		mov	cx, 0C80h

loc_1016A:				; CODE XREF: start+73j
		lodsw
		mov	dl, al
		lodsw
		mov	dh, al
		mov	ax, dx
		stosw
		loop	loc_1016A
		mov	cx, 1AE0h
		lea	si, [unk_10299]

loc_1017C:				; CODE XREF: start+98j
		mov	ax, [si-2]
		add	ax, [si]
		add	ax, [si+2]
		add	ax, [si+0A0h]
		sub	ax, bx
		sar	ax, 2
		jge	short loc_10191
		xor	ax, ax

loc_10191:				; CODE XREF: start+8Dj
		mov	[si-0A0h], ax
		add	si, 2
		loop	loc_1017C
		lea	si, [unk_137B9]
		mov	cx, 50h
		xor	dx, dx

loc_101A3:				; CODE XREF: start+BBj
		call	sub_101ED
		test	ax, ax
		js	short loc_101B2
		call	sub_101ED
		mov	dl, al
		and	dl, 7Fh

loc_101B2:				; CODE XREF: start+A8j
		mov	[si], dx
		mov	[si+0A0h], dx
		add	si, 2
		loop	loc_101A3
		mov	ah, 1
		int	16h		; KEYBOARD - CHECK BUFFER, DO NOT CLEAR
					; Return: ZF clear if character	in buffer
					; AH = scan code, AL = character
					; ZF set if no character in buffer
		jz	short loc_101CC
		mov	ah, 0
		int	16h		; KEYBOARD - READ CHAR FROM BUFFER, WAIT IF EMPTY
					; Return: AH = scan code, AL = character
		mov	bp, 0DACh
		jmp	short loc_101D2

; --------------- S U B	R O U T	I N E ---------------------------------------

loc_101CC:				; CODE XREF: start+C1j
		cmp	bp, 0DACh
		jb	short loc_1015E

loc_101D2:				; CODE XREF: start+CAj
		inc	bx
		cmp	bx, 64h
		jbe	short loc_1015E
		mov	ax, 3
		int	10h		; - VIDEO - SET	VIDEO MODE
					; AL = mode
		int	20h		; DOS -	PROGRAM	TERMINATION

; --------------- S U B	R O U T	I N E ---------------------------------------

sub_101DF:				; CODE XREF: start+31p
					; start:loc_1015Ep
		mov	dx, 3DAh

loc_101E2:				; CODE XREF: sub_101DF+6j
		in	al, dx		; Video	status bits:
					; 0: retrace.  1=display is in vert or horiz retrace.
					; 1: 1=light pen is triggered; 0=armed
					; 2: 1=light pen switch	is open; 0=closed
					; 3: 1=vertical	sync pulse is occurring.
		test	al, 8
		jz	short loc_101E2

loc_101E7:				; CODE XREF: sub_101DF+Bj
		in	al, dx		; Video	status bits:
					; 0: retrace.  1=display is in vert or horiz retrace.
					; 1: 1=light pen is triggered; 0=armed
					; 2: 1=light pen switch	is open; 0=closed
					; 3: 1=vertical	sync pulse is occurring.
		test	al, 8
		jnz	short loc_101E7
		retn

; --------------- S U B	R O U T	I N E ---------------------------------------

sub_101ED:				; CODE XREF: start:loc_101A3p
					; start+AAp
		mov	ax, [word_138F9]
		imul	ax, 8905h
		inc	ax
		mov	[word_138F9], ax
		retn

; ---------------------------------------------------------------------------

word_138F9:	dw 1234h		; DATA XREF: sub_101EDr sub_101ED+8w
unk_138FB:	db    0			; DATA XREF: start+34o
		db    0
		db    0
		db    0
		db    0
		db    2
		db    0
		db    0
		db    4
		db    0
		db    0
		db    6
		db    0
		db    0
		db    8
		db    0
		db    0
		db  0Ah
		db    0
		db    0
		db  0Ch
		db    0
		db    0
		db  0Eh
		db    0
		db    0
		db  10h
		db    2
		db    0
		db  0Eh
		db    4
		db    0
		db  0Ch
		db    6
		db    0
		db  0Ah
		db    8
		db    0
		db    8
		db  0Ah
		db    0
		db    6
		db  0Ch
		db    0
		db    4
		db  0Eh
		db    0
		db    2
		db  10h
		db    0
		db    0
		db  11h
		db    0
		db    0
		db  13h
		db    0
		db    0
		db  15h
		db    0
		db    0
		db  17h
		db    0
		db    0
		db  19h
		db    0
		db    0
		db  1Bh
		db    0
		db    0
		db  1Dh
		db    0
		db    0
		db  1Fh
		db    0
		db    0
		db  21h	; !
		db    0
		db    0
		db  23h	; #
		db    0
		db    0
		db  25h	; %
		db    0
		db    0
		db  27h	; '
		db    0
		db    0
		db  29h	; )
		db    0
		db    0
		db  2Bh	; +
		db    0
		db    0
		db  2Dh	; -
		db    0
		db    0
		db  2Fh	; /
		db    0
		db    0
		db  31h	; 1
		db    0
		db    0
		db  33h	; 3
		db    0
		db    0
		db  35h	; 5
		db    0
		db    0
		db  37h	; 7
		db    0
		db    0
		db  39h	; 9
		db    0
		db    0
		db  3Bh	; ;
		db    0
		db    0
		db  3Dh	; =
		db    0
		db    0
		db  3Fh	; ?
		db    0
		db    0
		db  3Fh	; ?
		db    1
		db    0
		db  3Fh	; ?
		db    3
		db    0
		db  3Fh	; ?
		db    5
		db    0
		db  3Fh	; ?
		db    7
		db    0
		db  3Fh	; ?
		db    9
		db    0
		db  3Fh	; ?
		db  0Bh
		db    0
		db  3Fh	; ?
		db  0Dh
		db    0
		db  3Fh	; ?
		db  0Fh
		db    0
		db  3Fh	; ?
		db  11h
		db    0
		db  3Fh	; ?
		db  13h
		db    0
		db  3Fh	; ?
		db  15h
		db    0
		db  3Fh	; ?
		db  17h
		db    0
		db  3Fh	; ?
		db  19h
		db    0
		db  3Fh	; ?
		db  1Bh
		db    0
		db  3Fh	; ?
		db  1Dh
		db    0
		db  3Fh	; ?
		db  1Fh
		db    0
		db  3Fh	; ?
		db  20h
		db    0
		db  3Fh	; ?
		db  22h	; "
		db    0
		db  3Fh	; ?
		db  24h	; $
		db    0
		db  3Fh	; ?
		db  26h	; &
		db    0
		db  3Fh	; ?
		db  28h	; (
		db    0
		db  3Fh	; ?
		db  2Ah	; *
		db    0
		db  3Fh	; ?
		db  2Ch	; ,
		db    0
		db  3Fh	; ?
		db  2Eh	; .
		db    0
		db  3Fh	; ?
		db  30h	; 0
		db    0
		db  3Fh	; ?
		db  32h	; 2
		db    0
		db  3Fh	; ?
		db  34h	; 4
		db    0
		db  3Fh	; ?
		db  36h	; 6
		db    0
		db  3Fh	; ?
		db  38h	; 8
		db    0
		db  3Fh	; ?
		db  3Ah	; :
		db    0
		db  3Fh	; ?
		db  3Ch	; <
		db    0
		db  3Fh	; ?
		db  3Fh	; ?
		db    0
		db  3Fh	; ?
		db  3Fh	; ?
		db    2
		db  3Fh	; ?
		db  3Fh	; ?
		db    5
		db  3Fh	; ?
		db  3Fh	; ?
		db    7
		db  3Fh	; ?
		db  3Fh	; ?
		db  0Ah
		db  3Fh	; ?
		db  3Fh	; ?
		db  0Dh
		db  3Fh	; ?
		db  3Fh	; ?
		db  0Fh
		db  3Fh	; ?
		db  3Fh	; ?
		db  12h
		db  3Fh	; ?
		db  3Fh	; ?
		db  15h
		db  3Fh	; ?
		db  3Fh	; ?
		db  17h
		db  3Fh	; ?
		db  3Fh	; ?
		db  1Ah
		db  3Fh	; ?
		db  3Fh	; ?
		db  1Ch
		db  3Fh	; ?
		db  3Fh	; ?
		db  1Fh
		db  3Fh	; ?
		db  3Fh	; ?
		db  22h	; "
		db  3Fh	; ?
		db  3Fh	; ?
		db  24h	; $
		db  3Fh	; ?
		db  3Fh	; ?
		db  27h	; '
		db  3Fh	; ?
		db  3Fh	; ?
		db  2Ah	; *
		db  3Fh	; ?
		db  3Fh	; ?
		db  2Ch	; ,
		db  3Fh	; ?
		db  3Fh	; ?
		db  2Fh	; /
		db  3Fh	; ?
		db  3Fh	; ?
		db  31h	; 1
		db  3Fh	; ?
		db  3Fh	; ?
		db  34h	; 4
		db  3Fh	; ?
		db  3Fh	; ?
		db  37h	; 7
		db  3Fh	; ?
		db  3Fh	; ?
		db  39h	; 9
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Ch	; <
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?
		db  3Fh	; ?

bss_start:

ABSOLUTE bss_start

alignb 2

unk_101F9:
		resb  160 
unk_10299:
		resb  13600
unk_137B9:	
		resb  320

_bss_end: